// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByblHEKIGhvlApW-3SVHzZNzqkoDABxjU',
    appId: '1:381192590305:web:02763d7fc59a0119a2f8a0',
    messagingSenderId: '381192590305',
    projectId: 'l3as1-8cefe',
    authDomain: 'l3as1-8cefe.firebaseapp.com',
    databaseURL: 'https://l3as1-8cefe-default-rtdb.firebaseio.com',
    storageBucket: 'l3as1-8cefe.appspot.com',
    measurementId: 'G-NQ91SCETHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7gjUfZ_pCGTHTaZ9PLWABEGB0Cxa8jYs',
    appId: '1:381192590305:android:c6aa6fb0b961f373a2f8a0',
    messagingSenderId: '381192590305',
    projectId: 'l3as1-8cefe',
    databaseURL: 'https://l3as1-8cefe-default-rtdb.firebaseio.com',
    storageBucket: 'l3as1-8cefe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8tPRjQeX_uKorolxI3ifFTiyVd1zAK6E',
    appId: '1:381192590305:ios:263e8a94124dc0d3a2f8a0',
    messagingSenderId: '381192590305',
    projectId: 'l3as1-8cefe',
    databaseURL: 'https://l3as1-8cefe-default-rtdb.firebaseio.com',
    storageBucket: 'l3as1-8cefe.appspot.com',
    iosBundleId: 'com.auraguidearchitecture.contemporaines',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8tPRjQeX_uKorolxI3ifFTiyVd1zAK6E',
    appId: '1:381192590305:ios:4a7861f994274b31a2f8a0',
    messagingSenderId: '381192590305',
    projectId: 'l3as1-8cefe',
    databaseURL: 'https://l3as1-8cefe-default-rtdb.firebaseio.com',
    storageBucket: 'l3as1-8cefe.appspot.com',
    iosBundleId: 'com.auraguidearchitecture.flutterapk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDimZbLQqJMDcO5xyue2LWcFwdPhg5xXpE',
    appId: '1:381192590305:web:270399aaa629b322a2f8a0',
    messagingSenderId: '381192590305',
    projectId: 'l3as1-8cefe',
    authDomain: 'l3as1-8cefe.firebaseapp.com',
    databaseURL: 'https://l3as1-8cefe-default-rtdb.firebaseio.com',
    storageBucket: 'l3as1-8cefe.appspot.com',
    measurementId: 'G-XHWMRXBDHL',
  );
}
